name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-lates
        steps:
        - name: welcome message
          run: echo "my first Github Actions Job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
